name: Build and Release (Windows)

on:
  push:
    tags:
      - "v*" # v1.0.0 のようなタグが push された時に実行

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Get commit message
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Get release body
        shell: bash
        run: |
          body=$(cat update.md)
          echo "body<<EOF" >> $GITHUB_ENV
          echo "$body" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Release を作成または取得
      - name: Create or get release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.message }}
          body: ${{ env.body }}
          draft: false
          prerelease: false
          allow_updates: true # 既存 Release があっても更新可能
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # バイナリをアップロード
      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: target/release/mb.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
